close all
clear all
%analysis of variation in Hela and MCF10a cells; 6 proteins are analyzed
%ERK, MEK, MCF5, MCF7, GAPDH and ENO

%Loads files generated by the Figure 4D program
load('File1')
vtot0=vtot; %individual cell intensities used to plot the histograms how variable ERK and MEK expression are
wtot0=wtot;
for k=1:2
    for i=1:9
        for j=1:3
            R0(3*(i-1)+j+(k-1)*27)=R(i,j,k); % variations for each well measured in HeLa cells
        end
    end
end

load('File2')
vtot0m=vtot;
wtot0m=wtot;
for k=1:2
    for i=1:9
        for j=1:3
            R0mcf(3*(i-1)+j+(k-1)*27)=R(i,j,k); % variations for each well measured in MCF10A cells
        end
    end
end


[p x]=hist(vtot0,.0:.025:1.9)
figure,bar(x,p)
v0=std(vtot0)/mean(vtot0);
title(['ERK variation: ' num2str(v0)])
[p x]=hist(wtot0,.0:.025:1.9)
figure,bar(x,p)
w0=std(wtot0)/mean(wtot0);
title(['MEK variation: ' num2str(w0)])

[p x]=hist(vtot0m,.0:.025:1.9)
figure,bar(x,p)
v0=std(vtot0m)/mean(vtot0m);
title(['ERK variation MCF10A: ' num2str(v0)])
[p x]=hist(wtot0m,.0:.025:1.9)
figure,bar(x,p)
w0=std(wtot0m)/mean(wtot0);
title(['MEK variation MCF10A: ' num2str(w0)])

%% 
ERKmcf=R0mcf([37:42 46:48]);
MEKmcf=R0mcf([10:18 52:54]);
MCM5mcf=R0mcf([28:30 34:36]);
MCM7mcf=R0mcf([1:3 31:33]);
GAPDHmcf=R0mcf([4:9 19:27 43:45]);
ENOmcf=R0mcf([49:51]);

B=[mean(ERKmcf) mean(MEKmcf) mean(MCM5mcf) mean(MCM7mcf) mean(GAPDHmcf) mean(ENOmcf)];
Berr=[std(ERKmcf) std(MEKmcf) std(MCM5mcf) std(MCM7mcf) std(GAPDHmcf) std(ENOmcf)];

% figure,bar(ENO)
% title('ENO')
figure, bar(100*B,'FaceColor',[0.7 .7 .7])
title('ERK,MEK,MCM5,MCM7,GAPDH,ENO')
ylabel('% variation in MCF10A cells')
hold on, errorbar(1:6,100*B,100*Berr,'.')
for i=1:length(ERKmcf)
    plot(.65+.7*(i-1)/length(ERKmcf),100*ERKmcf(i),'bo')
end
for i=1:length(MEKmcf)
    plot(1.65+.7*(i-1)/length(MEKmcf),100*MEKmcf(i),'bo')
end
for i=1:length(MCM5mcf)
    plot(2.65+.7*(i-1)/length(MCM5mcf),100*MCM5mcf(i),'bo')
end
for i=1:length(MCM7mcf)
    plot(3.65+.7*(i-1)/length(MCM7mcf),100*MCM7mcf(i),'bo')
end
for i=1:length(GAPDHmcf)
    plot(4.65+.7*(i-1)/length(GAPDHmcf),100*GAPDHmcf(i),'bo')
end
for i=1:length(ENOmcf)
    plot(5.65+.7*(i-1)/length(ENOmcf),100*ENOmcf(i),'bo')
end

%% 
ERK=R0([37:42 46:48]);
MEK=R0([13:15 52:54]);
MCM5=R0([28:30 34:36]);
MCM7=R0([1:3 31:33]);
GAPDH=R0([4:9 19:27 43:45]);
ENO=R0([49:51]);

A=[mean(ERK) mean(MEK) mean(MCM5) mean(MCM7) mean(GAPDH) mean(ENO)];
Aerr=[std(ERK) std(MEK) std(MCM5mcf) std(MCM7) std(GAPDH) std(ENO)];

figure, bar(100*A,'FaceColor',[0.7 .7 .7])
title('ERK,MEK,MCM5,MCM7,GAPDH,ENO')
ylabel('% variation in HeLa cells')
hold on, errorbar(1:6,100*A,100*Aerr,'.')
for i=1:length(ERK)
    plot(.65+.7*(i-1)/length(ERK),100*ERK(i),'bo')
end
for i=1:length(MEK)
    plot(1.65+.7*(i-1)/length(MEK),100*MEK(i),'bo')
end
for i=1:length(MCM5)
    plot(2.65+.7*(i-1)/length(MCM5),100*MCM5(i),'bo')
end
for i=1:length(MCM7)
    plot(3.65+.7*(i-1)/length(MCM7),100*MCM7(i),'bo')
end
for i=1:length(GAPDH)
    plot(4.65+.7*(i-1)/length(GAPDH),100*GAPDH(i),'bo')
end
for i=1:length(ENO)
    plot(5.65+.7*(i-1)/length(ENO),100*ENO(i),'bo')
end
