function [params, species] = erkInitialize()
% This file is automatically generated by updateModel.m from the ERK whole-cell spreadsheet
% Model URL: ERK reactions.xlsx


% PARAMETERS
params(1,1) = 1.66667e-06; % Raf & RasGTP binding
params(2,1) = 0.0053; % Raf & RasGTP dissociation
params(3,1) = 1; % Raf Activation
params(4,1) = 0.000118333; % Rafx & Phase1 binding
params(5,1) = 0.2; % Rafx & Phase1 dissoc.
params(6,1) = 1; % Rafx Deactivation
params(7,1) = 1.95463e-05; % MEK & Rafx Binding
params(8,1) = 0.033; % MEK & Rafx dissoc.
params(9,1) = 3.5; % MEK Phosphorylation
params(10,1) = 1.95463e-05; % MEK-P & Rafx Binding
params(11,1) = 0.033; % MEK-P & Rafx Dissociation
params(12,1) = 2.9; % MEK-P Phosphorylation
params(13,1) = 2.38333e-05; % MEK-PP & Phase2 Binding
params(14,1) = 0.8; % MEK-PP & Phase2 Dissociation
params(15,1) = 0.058; % MEK-PP Desphosphorylation
params(16,1) = 4.5e-07; % MEK-P & Phase2 Binding
params(17,1) = 0.5; % MEK-P & Phase2 Dissociation
params(18,1) = 0.058; % MEK-P Desphosphorylation
params(19,1) = 8.90722e-05; % ERK & MEK-PP Binding
params(20,1) = 0.01833; % ERK & MEK-PP Dissociation
params(21,1) = 16; % ERK Phosphorylation
params(22,1) = 8.90722e-05; % ERK-P & MEK-PP Binding
params(23,1) = 0.01833; % ERK-P & MEK-PP Dissociation
params(24,1) = 5.7; % ERK-P Phosphorylation
params(25,1) = 2.35e-05; % ERK-PP & Phase3 Binding
params(26,1) = 0.6; % ERK-PP & Phase3 Dissociation
params(27,1) = 0.246; % ERK-PP Desphosphorylation
params(28,1) = 8.33333e-06; % ERK-P & Phase3 Binding
params(29,1) = 0.5; % ERK-P & Phase3 Dissociation
params(30,1) = 0.246; % ERK-P Desphosphorylation
params(31,1) = 1e-07; % ERK-PP & Rafx Binding
params(32,1) = 1; % ERK-PP & Rafx Dissociation
params(33,1) = 10; % Rafx Hyper-Phosphorylation
params(34,1) = 1e-07; % ERK-PP & Raf Binding
params(35,1) = 1; % ERK-PP & Raf Dissociation
params(36,1) = 10; % Raf Hyper-Phosphorylation
params(37,1) = 5e-05; % Rafp & Phase 4 Binding
params(38,1) = 0.2; % Rafp & Phase 4 Dissociation
params(39,1) = 0.5; % Rafp De-Phosphorylation


% SPECIES
species.NAMES = {...
'Raf' ...1
'RasGTP' ...2
'Raf_RasGTP' ...3
'Rafx' ...4
'Phase1' ...5
'Rafx_Phase1' ...6
'MEK' ...7
'MEK_Rafx' ...8
'MEKp' ...9
'MEKp_Rafx' ...10
'MEKpp' ...11
'Phase2' ...12
'MEKpp_Phase2' ...13
'MEKp_Phase2' ...14
'ERK' ...15
'ERK_MEKpp' ...16
'ERKp' ...17
'ERKpp' ...18
'ERKp_MEKpp' ...19
'Phase3' ...20
'ERKpp_Phase3' ...21
'ERKp_Phase3' ...22
'ERKpp_Rafx' ...23
'Rafp' ...24
'ERKpp_Raf' ...25
'Phase4' ...26
'Rafp_Phase4' ...27
};